"""
Body-shape validation / calibration harness (tabular).

Body shape is DETERMINISTIC (app/measure_core.classify_body_shape — bust/waist/hip/shoulder
ratios, sex-aware) — the same logic as the shared classifier, so no training. This runs OUR
canonical classifier over a CSV of anthropometric measurements (e.g. exported from IndiaSize /
Indian Anthropometric Dimensions) to produce the "early info" for validation + calibration:
the body-shape distribution for the population, WHR/WHtR summaries, and how many rows fall
OUTSIDE our plausibility ranges (`measure_core.PLAUSIBLE_CIRC_CM`) — which is what to widen
for an Indian-first fit.  See docs/body_data_plan.md.

CSV columns (case-insensitive; cm): chest|bust, waist, hip, [shoulder|shoulder_width],
[sex] (1=male,2=female; default 2), [height].

    python -m bench.body_shape_report --csv data/indiasize/adults.csv --name indiasize
"""
from __future__ import annotations
import argparse
import csv
import json
import os
import statistics
from collections import Counter

from app.measure_core import classify_body_shape, PLAUSIBLE_CIRC_CM


def _f(row, *names):
    for n in names:
        for k in row:
            if k.strip().lower() == n and str(row[k]).strip() not in ("", "NA", "nan"):
                try:
                    return float(row[k])
                except ValueError:
                    return None
    return None


def _row_to_measurements(row):
    chest = _f(row, "chest", "bust")
    waist = _f(row, "waist")
    hip = _f(row, "hip", "hips")
    shoulder_w = _f(row, "shoulder_width", "shoulder")
    sex = int(_f(row, "sex") or 2)
    height = _f(row, "height", "stature")
    m = {}
    if chest is not None:
        m["chest"] = {"circumference_cm": chest}
    if waist is not None:
        m["waist"] = {"circumference_cm": waist}
    if hip is not None:
        m["hip"] = {"circumference_cm": hip}
    if shoulder_w is not None:
        m["shoulder"] = {"width_cm": shoulder_w}
    return m, sex, waist, hip, height


def _out_of_range(m):
    flags = []
    for part, mm in m.items():
        c = mm.get("circumference_cm")
        if c is None:
            continue
        lo, hi = PLAUSIBLE_CIRC_CM.get(part, (0.0, float("inf")))
        if not (lo <= c <= hi):
            flags.append(part)
    return flags


def run_report(csv_path, name="dataset", out_dir="data/reports", limit=None):
    shapes = Counter()
    n = oob = 0
    whr, whtr = [], []
    with open(csv_path, newline="") as f:
        for i, row in enumerate(csv.DictReader(f)):
            if limit and i >= limit:
                break
            m, sex, waist, hip, height = _row_to_measurements(row)
            res = classify_body_shape(m, sex)
            shapes[res.get("shape", "insufficient_data")] += 1
            n += 1
            if _out_of_range(m):
                oob += 1
            if waist and hip:
                whr.append(waist / hip)
            if waist and height:
                whtr.append(waist / height)
    summary = {
        "dataset": name,
        "n_rows": n,
        "shape_distribution": dict(shapes.most_common()),
        "out_of_plausible_range": oob,
        "out_of_range_rate": round(oob / n, 3) if n else None,
        "whr_mean": round(statistics.fmean(whr), 3) if whr else None,          # waist:hip
        "whtr_mean": round(statistics.fmean(whtr), 3) if whtr else None,        # waist:height (>0.5 flag)
        "note": "Shape from measure_core.classify_body_shape (deterministic). Use out-of-range "
                "rate to recalibrate PLAUSIBLE_CIRC_CM / size charts for the Indian population; "
                "never prior an individual's shape by ethnicity (fit must be exact).",
    }
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, f"{name}.json"), "w") as f:
        json.dump(summary, f, indent=2)
    with open(os.path.join(out_dir, f"{name}.md"), "w") as f:
        f.write(_to_markdown(summary) + "\n")
    return summary


def _to_markdown(s):
    L = [f"# Body-shape report — {s['dataset']}", "",
         f"- rows: **{s['n_rows']}**",
         f"- out of plausible range: **{s['out_of_plausible_range']}** ({s['out_of_range_rate']})",
         f"- WHR mean (waist:hip): {s['whr_mean']}   ·   WHtR mean (waist:height): {s['whtr_mean']}",
         "", "## Shape distribution", ""]
    for k, v in s["shape_distribution"].items():
        L.append(f"- {k}: {v}")
    L += ["", f"_{s['note']}_", "", "_Generated by bench/body_shape_report.py — see docs/body_data_plan.md._"]
    return "\n".join(L)


def main(argv=None):
    ap = argparse.ArgumentParser(description="Krey body-shape validation/calibration report.")
    ap.add_argument("--csv", required=True, help="anthropometric CSV (chest/bust,waist,hip[,shoulder,sex,height])")
    ap.add_argument("--name", default="dataset")
    ap.add_argument("--out", default="data/reports")
    ap.add_argument("--limit", type=int, default=None)
    a = ap.parse_args(argv)
    print(json.dumps(run_report(a.csv, name=a.name, out_dir=a.out, limit=a.limit), indent=2))


if __name__ == "__main__":
    main()
